package pojos;
// Generated Jan 15, 2020 1:37:05 PM by Hibernate Tools 4.3.1



/**
 * UserTbl generated by hbm2java
 */
public class UserTbl  implements java.io.Serializable {


     private int idUser;
     private String name;
     private String gender;
     private String adress;

    public UserTbl() {
    }

    public UserTbl(int idUser, String name, String gender, String adress) {
       this.idUser = idUser;
       this.name = name;
       this.gender = gender;
       this.adress = adress;
    }
   
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getAdress() {
        return this.adress;
    }
    
    public void setAdress(String adress) {
        this.adress = adress;
    }




}


